#!/bin/sh

# this code is statically linked with lib_sh

func_check_file_general_exist()
{
    if [ ! -e "$1" ]; then
        echo "file $1 not found. exit."
        exit 1
    fi
}

this_link="$(basename "$0")"
dir_target=/tmp/"${this_link}".d


func_main()
{
    echo "start $0"

    func_check_file_general_exist /vmlinuz

    rm -rf   "${dir_target}"
    mkdir -p "${dir_target}"

    cp -f                       \
        /vmlinuz                \
        "${dir_target}"/vmlinuz \
        ;

    echo "done $0"
}

func_main "$@"

