#!/bin/sh

# this code is statically linked with lib_sh

# bugs
#   these settings cause /usr/bin/xz to be excluded from the archive
#   -comp xz \
#   -comp xz -Xdict-size 100% \

func_check_user_not_root()
{
    if [ "$(id -u)" = "0" ]; then
        echo "this script should not run by root. exit."
        exit 1
    fi
}

func_check_user_not_root
this_link="$(basename "$0")"
dir_target=/tmp/"${this_link}".d


func_build_root()
{
    myfn="${dir_target}/root.squashfs"
    sudo rm "${myfn}"
    sudo mksquashfs                 \
        /bin /sbin /lib* /usr /etc /var /opt /root /home \
        "${myfn}"                   \
                                    \
        -e ~/mnt                    \
        -e ~/ramfs                  \
        -e ~/.local/share/ranger    \
        -e ~/.local/share/zathura   \
                                    \
        -b 1024K                    \
        -always-use-fragments       \
        -keep-as-directory          \
        ;
}

func_main()
{
    rm -rf   "${dir_target}"
    mkdir -p "${dir_target}"

    func_build_root

    echo "done $0"
}

func_main "$@"

