#!/bin/sh -x

# do not set "-e" flag

func_check_file_general_exist()
{
    if [ ! -e "$1" ]; then
        echo "file $1 not found. exit."
        exit 1
    fi
}

this_abs_dir="$(cd "$(dirname "$0")" && pwd)"
cd "${this_abs_dir}" || exit 1

mymount="/m1"
mylayer0="${mymount}"/layer0_squashfs


func_main()
{
    myfn1="$1"
    myfn1_enc="$(basename "${myfn}")_enc"
    func_check_file_general_exist "${myfn1}"

    cryptsetup open "${myfn1}" "${myfn1_enc}"       || exit 1
    mount /dev/mapper/"${myfn1_enc}" "${mylayer0}"  || exit 1

    echo "done $0"
}

func_main "$@"

